# Generated by Django 2.0.8 on 2018-10-19 07:42

import apps.user.models.user
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', apps.user.models.user.UserManager()),
            ],
        ),
    ]
