version: '3'

services:
  db:
    image: postgres:9.6.5
    volumes:
      - psql-data:/var/lib/postgresql/data
      - .:/application
  web:
    build: .
    working_dir: /application/server
    env_file:
      - server/config/settings/.env
    # command: "tail -f /dev/null"
    command: ["bash", "docker_entry.sh", "python3", "manage.py", "runserver", "0:8000"]
    volumes:
      - .:/application
      - app-python-site-packages:/usr/local/lib/python3.7/site-packages
      - app-usr-local-bin:/usr/local/bin
      - ~/.ssh:/root/.ssh
    ports:
      - "9095:8000"
    depends_on:
      - db

volumes:
  app-python-site-packages:
    driver: local
  psql-data:
    driver: local
  app-usr-local-bin:
    driver: local
